library('shiny')

ui <- fluidPage(
  shiny::tags$h1('rMATS-long'),
  shiny::tags$h2('Differential transcript usage result files'),
  shiny::downloadButton('download_diff_transcripts', 'download differential_transcripts.tsv'),
  shiny::downloadButton('download_diff_genes', 'download differential_genes.tsv'),
  shiny::tags$h2('Parameters'),
  shiny::selectInput('dataset_select', 'select dataset', choices=base::c('')),
  shiny::textOutput('sample_names'),
  shiny::selectInput('group_1_samples', 'select group 1 samples',
                     choices=base::c(''), multiple=TRUE),
  shiny::textInput('group_1_name', 'group 1 name', value='group 1'),
  shiny::selectInput('group_2_samples', 'select group 2 samples',
                     choices=base::c(''), multiple=TRUE),
  shiny::textInput('group_2_name', 'group 2 name', value='group 2'),
  shiny::textInput('gene_name', 'gene name', value=''),
  shiny::textInput('gene_id', 'gene ID', value=''),
  shiny::numericInput('intron_scaling', 'intron scaling', 1, min=1, step=1),
  shiny::actionButton('plot_button', 'create plots'),
  shiny::tags$h2('Results'),
  shiny::tags$h3('Abundance'),
  shiny::imageOutput('abundance_image', width=800, height=600),
  shiny::downloadButton('abundance_png', 'download .png'),
  shiny::downloadButton('abundance_pdf', 'download .pdf'),
  shiny::tags$h3('Structure'),
  shiny::imageOutput('structure_image', width=800, height=300),
  shiny::downloadButton('structure_png', 'download .png'),
  shiny::downloadButton('structure_pdf', 'download .pdf'),
  shiny::tags$h3('Differential transcripts'),
  shiny::tableOutput('differential_transcripts'),
  shiny::tags$h3('Isoform differences'),
  shiny::textInput('transcript_id', 'transcript ID', value=''),
  shiny::actionButton('classify_button', 'classify isoform differences'),
  shiny::tableOutput('isoform_differences'),
  shiny::downloadButton('updated_gtf', 'download detected isoform .gtf'),
)
